package com.learning.shared.exception;

import org.apache.log4j.Logger;
import org.springframework.web.bind.annotation.ControllerAdvice;
import org.springframework.web.bind.annotation.ExceptionHandler;
import org.springframework.web.bind.annotation.RestController;

import com.learning.shared.bean.ResponseBean;
import com.learning.shared.constant.StatusCode;
import com.learning.shared.util.JsonUtil;

@RestController
@ControllerAdvice
public class GlobalExceptionHandler {
	
	
	private final static Logger logger = Logger.getLogger(GlobalExceptionHandler.class);
	
	@ExceptionHandler(NullPointerException.class)
	public ResponseBean<String> nullPointerException(NullPointerException exception) {
		StackTraceElement elt = Thread.currentThread().getStackTrace()[2];
		logger.debug(elt.getClassName() + "::" + elt.getMethodName() + ":" + elt.getLineNumber() + " - " + exception);
		ResponseBean<String> responseBean = JsonUtil.createResponseBean(StatusCode.INTERNAL_SERVER_ERROR,"Somthing went wrong please try again!!",null);
		return responseBean;
	}
}
